import { PropertyLead, ProcessResponse } from '../types';

export function generateMockResponse(messageCount: number): ProcessResponse {
  const mockLeads: PropertyLead[] = [
    {
      property_id: 'PROP-001',
      property_type: 'Rental',
      owner_name: 'Rajesh Kumar',
      owner_contact: '9876543210',
      area: 'Koregaon Park',
      address: 'North Main Road, near ABC Mall',
      size: '2 BHK, 1200 sqft',
      rent_or_sell_price: '₹35,000/month',
      deposit: '₹70,000',
      date_stamp: '2026-04-10',
    },
    {
      property_id: 'PROP-002',
      property_type: 'Resale',
      owner_name: 'Priya Sharma',
      owner_contact: '9123456789',
      area: 'Baner',
      address: 'Baner Road, Opposite XYZ Complex',
      size: '3 BHK, 1800 sqft',
      rent_or_sell_price: '₹1.2 Cr',
      deposit: 'N/A',
      date_stamp: '2026-04-10',
    },
    {
      property_id: 'PROP-003',
      property_type: 'Rental',
      owner_name: 'Amit Patel',
      owner_contact: '9988776655',
      area: 'Hinjewadi',
      address: 'Phase 2, IT Park Road',
      size: '2 BHK, 1100 sqft',
      rent_or_sell_price: '₹28,000/month',
      deposit: '₹56,000',
      date_stamp: '2026-04-11',
    },
    {
      property_id: 'PROP-004',
      property_type: 'Resale',
      owner_name: 'Neha Singh',
      owner_contact: '9445566778',
      area: 'Wakad',
      address: 'Main Street, Tower A',
      size: '2 BHK, 1300 sqft',
      rent_or_sell_price: '₹85 Lakh',
      deposit: 'N/A',
      date_stamp: '2026-04-11',
    },
    {
      property_id: 'PROP-005',
      property_type: 'Rental',
      owner_name: 'Vikram Desai',
      owner_contact: 'N/A',
      area: 'Viman Nagar',
      address: 'Airport Road, near Terminal',
      size: '3 BHK, 1600 sqft',
      rent_or_sell_price: '₹42,000/month',
      deposit: '₹84,000',
      date_stamp: '2026-04-11',
    },
    {
      property_id: 'PROP-006',
      property_type: 'Rental',
      owner_name: 'Sanjay Mehta',
      owner_contact: '9334455667',
      area: 'Kharadi',
      address: 'EON IT Park vicinity',
      size: '2 BHK, 1250 sqft',
      rent_or_sell_price: '₹32,000/month',
      deposit: '₹64,000',
      date_stamp: '2026-04-09',
    },
    {
      property_id: 'PROP-007',
      property_type: 'Resale',
      owner_name: 'Anita Reddy',
      owner_contact: '9556677889',
      area: 'Aundh',
      address: 'Aundh Road, near Metro',
      size: '3 BHK, 2000 sqft',
      rent_or_sell_price: '₹1.8 Cr',
      deposit: 'N/A',
      date_stamp: '2026-04-09',
    },
    {
      property_id: 'PROP-008',
      property_type: 'Rental',
      owner_name: 'Ramesh Kulkarni',
      owner_contact: '9667788990',
      area: 'Pimple Saudagar',
      address: 'Main Road, Phase 3',
      size: '2 BHK, 1150 sqft',
      rent_or_sell_price: '₹26,000/month',
      deposit: '₹52,000',
      date_stamp: '2026-04-08',
    },
  ];

  return {
    rows: mockLeads,
    metadata: {
      message_count: messageCount,
      parsed_count: mockLeads.length,
      ai_fallback_used: false,
      processing_time: 1.23,
      failed_messages: [
        {
          message_index: 5,
          date_stamp: '2026-04-11',
          missing_fields: ['owner_contact', 'rent_or_sell_price'],
          raw_message:
            '[11/04/2026, 14:30:00] Unknown: Property available in Hadapsar',
        },
      ],
    },
  };
}
